version: '3'

services:
  app:
    build: ./
    restart: unless-stopped
    volumes:
      - static:/code/app/static
    ports:
      - 5000:80
    environment:
      - LOGLEVEL=debug

volumes:
  static:
